runtime: python312
instance_class: F2
entrypoint: gunicorn -b :$PORT app:app --timeout 300 --workers 1 --threads 4

automatic_scaling:
  min_instances: 0
  max_instances: 2

handlers:
  - url: /static
    static_dir: static
    secure: always
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
