runtime: python312
instance_class: F1
entrypoint: gunicorn -b :$PORT app:app --timeout 120 --workers 2
automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
  - url: /static
    static_dir: static
    secure: always
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
